version: '3.8'

services:
  iam-db:
    image: postgres:16.0-alpine
    volumes:
      - iam-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: iam-dev
      POSTGRES_USER: iam-user
      POSTGRES_PASSWORD: iam-secret

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev
    depends_on:
      - iam-db
    ports:
      - '8090:8080'
    environment:
      KEYCLOAK_ADMIN: kc-admin
      KEYCLOAK_ADMIN_PASSWORD: kc-admin-secret
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: iam-user
      KC_DB_PASSWORD: iam-secret
      KC_DB_URL: jdbc:postgresql://iam-db:5432/iam-dev
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz

volumes:
  iam-data: